#!/bin/bash

<< DETAILS
    Author: GrimIrani
    Date: 2021-11-28
    Lisense: NPLv1
    Source: https://github.com/GrimIrani/reip
    
    binaries:
        Sing-box:   v2.0
        v2ray-core: v2.0
        openvpn:    v2.6
        wireguard:  v2.0
DETAILES

